openapi: 3.0.1
info:
  title: PizzaShack
  version: 1.0.0
servers:
- url: /
security:
- default: []
paths:
  /menu:
    get:
      summary: Return menu items
      description: |
        Return a list of menu items
      parameters: []
      responses:
        "200":
          description: ok
      security:
      - default:
        - order_pizza
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /order:
    post:
      parameters: []
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /order/{orderid}:
    get:
      parameters:
      - name: orderid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    put:
      parameters:
      - name: orderid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes:
            order_pizza: Only users with admin role and Internal/subscriber role can
              order
          x-scopes-bindings:
            order_pizza: admin,internal/subscriber
